# -*- coding: utf-8 -*-
"""
apply_rename.py -- one-off rename pass: iptv-r3zound -> iptv-desktop.

Edits in place:
  - tools/iptv-desktop.py           (string contents; file already renamed)
  - README.md / AGENTS.md
  - tools/build_icons.py            (comments only)
  - tools/build_page.py             (HTML title only)
  - assets/icons/preview.html       (HTML title only)
Deletes:
  - tools/iptv-r3zound.spec         (stale build artifact)
Writes:
  - .gitignore                      (python + pyinstaller + cache exclusions)
"""
from __future__ import annotations

import io
import os
import shutil
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# (path, [(old, new), ...])
EDITS = [
    ("tools/iptv-desktop.py", [
        ("# iptv-r3zound.py -- main entry point.", "# iptv-desktop.py -- main entry point."),
        ("usage: iptv-r3zound.exe [OPTIONS]",
         "usage: iptv-desktop.exe [OPTIONS]"),
        ("iptv-r3zound -- \u9519\u8bef",
         "iptv-desktop -- \u9519\u8bef"),
        ("generated by iptv-r3zound at",
         "generated by iptv-desktop at"),
        ("iptv-r3zound -- \u64ad\u653e\u5668\u672a\u627e\u5230",
         "iptv-desktop -- \u64ad\u653e\u5668\u672a\u627e\u5230"),
        ("iptv-r3zound -- \u62a5\u9519",
         "iptv-desktop -- \u62a5\u9519"),
        ("iptv-r3zound -- \u4f7f\u7528\u672c\u5730\u7f13\u5b58",
         "iptv-desktop -- \u4f7f\u7528\u672c\u5730\u7f13\u5b58"),
    ]),
    ("README.md", [
        ("# IPTV-r3zound\n", "# iptv-desktop\n"),
        ("dist/iptv-r3zound-portable", "dist/iptv-desktop-portable"),
        ("iptv-r3zound.exe", "iptv-desktop.exe"),
        ("iptv-r3zound-portable\\", "iptv-desktop-portable\\"),
        ("    iptv-r3zound.log", "    iptv-desktop.log"),
        ("dist\\iptv-r3zound-portable", "dist\\iptv-desktop-portable"),
        ("cache\\iptv-r3zound.log", "cache\\iptv-desktop.log"),
    ]),
    ("AGENTS.md", [
        ("# AGENTS.md -- IPTV-r3zound\n", "# AGENTS.md -- iptv-desktop\n"),
        ("(`iptv-r3zound.log`)", "(`iptv-desktop.log`)"),
        ("iptv-r3zound.py        <- main entry",
         "iptv-desktop.py        <- main entry"),
        ("2026-09-17 onwards: **`IPTV-r3zound`** (personal signature)",
         "2026-09-17 onwards: **`iptv-desktop`** (personal signature)"),
        ("IPTV-r3zound/\n", "iptv-desktop/\n"),
    ]),
    ("tools/build_icons.py", [
        ("\u4f9b iptv-r3zound.exe \u9009\u7528",
         "\u4f9b iptv-desktop.exe \u9009\u7528"),
    ]),
    ("tools/build_page.py", [
        ("iptv-r3zound \u56fe\u6807\u5019\u9009",
         "iptv-desktop \u56fe\u6807\u5019\u9009"),
    ]),
    ("assets/icons/preview.html", [
        ("iptv-r3zound \u56fe\u6807\u5019\u9009",
         "iptv-desktop \u56fe\u6807\u5019\u9009"),
    ]),
]


def patch(path, edits):
    full = os.path.join(ROOT, path)
    with io.open(full, "r", encoding="utf-8") as f:
        text = f.read()
    misses = []
    for old, new in edits:
        if old in text:
            text = text.replace(old, new)
        else:
            misses.append(old)
    if misses:
        print(f"  [WARN] {path}: {len(misses)} old_string not found")
        for m in misses[:3]:
            print(f"    - {m[:80]}")
    with io.open(full, "w", encoding="utf-8") as f:
        f.write(text)
    print(f"  [OK]   {path}")


def main():
    print("== apply edits ==")
    for path, edits in EDITS:
        patch(path, edits)
    spec = os.path.join(ROOT, "tools", "iptv-r3zound.spec")
    if os.path.exists(spec):
        os.remove(spec)
        print(f"  [DEL]  tools/iptv-r3zound.spec")
    print("done.")


if __name__ == "__main__":
    main()