#!/usr/bin/env python3
# make_seed.py -- build a high-quality seed cache for the portable zip.
#
# Reads the raw playlist from a source cache, runs it through the full
# V9 pipeline (URL blocklist -> exclude_non_chinese ->
# exclude_geo_blocked -> full HEAD probe -> tier sort -> per-channel
# cap), and writes the result to <root>/seed_cache/.
#
# The seed is what make_portable.py ships inside the zip, so a freshly
# extracted portable folder can open a working playlist even when the
# network is unavailable.
#
# Usage (from tools/):
#     python archive/make_seed.py
from __future__ import annotations

import os
import sys
import time

_HERE = os.path.dirname(os.path.abspath(__file__))
_TOOLS = os.path.normpath(os.path.join(_HERE, ".."))
_ROOT = os.path.dirname(_TOOLS)
sys.path.insert(0, _TOOLS)

from core import cache, filters, merge, playlist, progress  # noqa: E402


def _find_raw_playlist() -> str:
    """Locate the raw (unfiltered) playlist to use as seed input."""
    candidates = (
        os.path.join(_TOOLS, "cache", "best_sorted.m3u"),
        os.path.join(_ROOT, "cache", "best_sorted.m3u"),
        os.path.join(_ROOT, "dist", "iptv-desktop-portable", "cache", "best_sorted.m3u"),
    )
    for c in candidates:
        if os.path.isfile(c) and os.path.getsize(c) > 1000:
            return c
    return ""


def main() -> int:
    raw = _find_raw_playlist()
    if not raw:
        print("[seed] no raw playlist found -- cannot build seed")
        return 1

    print("[seed] input: %s" % raw)
    with open(raw, "rb") as f:
        data = f.read()
    entries = playlist.parse(data, source="raw")
    print("[seed] parsed %d entries" % len(entries))

    # Use the ini defaults but with probe_mode="sample".
    #
    # Why not "full": full HEAD probing is DNS-bound in practice.
    # Python 3.8's socket.getaddrinfo() has no timeout, so an
    # unresponsive DNS server blocks each worker for tens of seconds
    # regardless of the urllib timeout. Over ~8k URLs that turns a
    # 2-minute job into a 15-minute one. Sample mode drops obviously
    # dead tiers in seconds, which is the right trade-off for a seed
    # that only matters when the network is already broken.
    fcfg = filters.FilterConfig(
        url_patterns=filters.parse_filter_config(_dummy_cfg()).url_patterns,
        probe_mode="sample",
        probe_sample_size=10,
        probe_timeout=1.5,
        probe_concurrency=24,
        probe_min_success_rate=0.20,
        exclude_non_chinese=True,
        exclude_geo_blocked=True,
    )
    print("[seed] filters: %s" % fcfg)

    sink = progress.ConsoleSink()
    t0 = time.time()
    merged = merge.merge(
        [entries],
        per_channel_cap=3,
        filter_cfg=fcfg,
        sink=sink,
    )
    print("[seed] merged %d entries in %.1fs" % (merged and len(merged), time.time() - t0))

    if not merged:
        print("[seed] empty result -- refusing to write a seed")
        return 1

    out_bytes = playlist.serialize(
        merged,
        header="# seed generated by make_seed.py at %s"
               % time.strftime("%Y-%m-%dT%H:%M:%S"),
    )
    s = merge.stats(merged)

    seed_dir = os.path.join(_ROOT, "seed_cache")
    os.makedirs(seed_dir, exist_ok=True)
    with open(os.path.join(seed_dir, "best_sorted.m3u"), "wb") as f:
        f.write(out_bytes)

    import json
    with open(os.path.join(seed_dir, "meta.json"), "w", encoding="utf-8") as f:
        json.dump({
            "source_url": "seed (offline fallback)",
            "fetched_at": time.strftime("%Y-%m-%dT%H:%M:%S"),
            "channel_count": len(merged),
            "per_channel_cap": 3,
            "by_tier": s["by_tier"],
            "by_source": s["by_source"],
            "meta_version": 1,
            "saved_at": int(time.time()),
            "file_size": len(out_bytes),
        }, f, ensure_ascii=False, indent=2)

    print("[seed] wrote %s (%d bytes, %d channels)" % (
        seed_dir, len(out_bytes), len(merged)
    ))
    print("[seed] by_tier: %s" % s["by_tier"])
    return 0


def _dummy_cfg():
    """Minimal configparser holding the built-in filter defaults."""
    import configparser
    cfg = configparser.ConfigParser()
    # Empty [filters] section -> parse_filter_config falls back to
    # DEFAULT_URL_BLOCKLIST, which is exactly what we want.
    cfg.add_section("filters")
    return cfg


if __name__ == "__main__":
    sys.exit(main())
